default_platform :android

#Crashlytics
ENV['CRASHLYTICS_API_TOKEN']        = "f984f3a695c3cdd7cd6a38475b6d30b7f398ce4d"
ENV['CRASHLYTICS_BUILD_SECRET']     = "656d6a02a40d9c035b98871873ca71ce43a897cb6b14cd996b323d8b2c5851b8"
ENV['CRASHLYTICS_GROUPS']           = "rs6internalandroid"

#Slack
ENV['SLACK_URL']                    = "https://hooks.slack.com/services/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"
ENV['FL_SLACK_CHANNEL']             = "#rainboxsix-app"

desc "This lane builds an APK, submit it to Fabric and add a message in the rainboxsix-app slack channel"
  lane :deploy do

    increment_version_code()

	gradle(
		task: 'assemble',
		build_type: 'Release'
	)

	ApkPath = lane_context[SharedValues:: GRADLE_APK_OUTPUT_PATH]

	# Ask the user of fastlane to enter a changelog
    changelog = prompt(text: "Enter the release note for Crashlytics: ",
                       multi_line_end_keyword: "END")


    crashlytics(
     	apk_path: ApkPath,
		notes: changelog
    )


    VersionName = get_version_name

    VersionCode = get_version_code

	slackMessageString = "🚀🚀🚀 New version of RainbowSix App #{VersionName} (#{VersionCode}) available on Fabric 🚀🚀🚀"

	slack(
		message: slackMessageString,
		default_payloads: [],
		payload: {
		    "Changes" => changelog
		}
	)

	# Commit, tag and push to git
    git_add(path: ".")
    git_commit(path: ".", message: "Version bump")
    add_git_tag(prefix: "build.")
    push_to_git_remote

end
